### PR TITLE
j2objc: style nits

### PR DESCRIPTION
**Pull request by DomT4**
Style nits. This PR is largely a test to see if the merge conflict is occuring everywhere.

### CODE REVIEW

**Comment by DomT4** [comment]
Cringe. This one failed for the same reason as the other @mikemcquaid. Something about this repository is off. Maybe I set it up wrong at the start, garg.

**Comment by mikemcquaid** [comment]
Ah, the `brew pull` regex is failing I bet.

**Comment by mikemcquaid** [comment]
Passing now.

**Comment by DomT4** [comment]
You are *awesome*. Thanks!

**Pull request closed without merging**
