### PR TITLE
mlite: testing the bot

### PR DESCRIPTION
**Pull request by DomT4**
Ignore this PR. Do not merge it. Just a test run.

### CODE REVIEW

**Comment by DomT4** [comment]
Test bot:

```
==> brew update								 PASSED
==> git checkout 0875c63						 PASSED
==> brew pull --clean https://github.com/Homebrew/homebrew-devel-only/pull/10 PASSED
==> brew doctor								 PASSED
==> brew --env								 PASSED
==> brew config								 PASSED
==> brew tests								 PASSED
==> brew readall							 PASSED
==> brew uses mlite							 PASSED
==> brew fetch --retry --build-bottle --force mlite			 PASSED
==> brew install --verbose --build-bottle mlite				 FAILED
Error: mlite is a devel-only formula
Install with `brew install --devel mlite`
==> brew audit mlite							 FAILED
Error: 1 problems in 1 formulae
mlite:
 * Devel-only (no stable download)

==> git clean -fdx							 PASSED
==> git checkout -f master						 PASSED
==> git reset --hard							 PASSED
==> brew cleanup							 PASSED
```

Locally with ` brew pull --clean https://github.com/Homebrew/homebrew-devel-only/pull/10 ` and ` brew test-bot --skip-setup mlite `:

```
==> brew tests								 PASSED
==> brew readall							 PASSED
==> brew uses mlite							 PASSED
==> brew fetch --retry --build-bottle mlite				 PASSED
==> brew install --verbose --build-bottle --devel mlite			 PASSED
==> brew audit mlite							 PASSED
==> brew bottle --rb mlite						 FAILED
Error: Formula has no stable version: mlite
==> brew test --verbose mlite						 PASSED
==> brew uninstall --force mlite					 PASSED
```

**Comment by DomT4** [comment]
@mikemcquaid Re earlier conversation:

```
      if devel_only_tap? formula
        install_args << "--devel"
        puts formula.tap
      elsif head_only_tap? formula
        install_args << "--HEAD"
        puts formula.tap
      end
```

We get:

```
brew test-bot --dry-run --skip-setup mlite
==> brew tests
==> brew readall
==> brew uses mlite
==> brew fetch --retry --build-bottle mlite
homebrew/homebrew-devel-only
==> brew install --verbose --build-bottle --devel mlite
==> brew audit mlite
==> brew bottle --rb mlite
==> brew test --verbose mlite
==> brew uninstall --force mlite
```

Seems to cough out the expected response for ` HEAD ` as well:

```
==> brew uses adept
==> brew fetch --retry --build-bottle adept
homebrew/homebrew-head-only
==> brew install --verbose --build-bottle --HEAD adept
==> brew audit adept
```

Any thoughts? Did I manage to actually follow your advice a little better after I went away and mainlined caffeine for a while? :wink:

**Comment by mikemcquaid** [comment]
Hmm, I'm still not sure I'm afraid. I reckon maybe try making a test PR in core with a devel-only and head-only formula and commenting out the tap-specific bits in `test-bot.rb` temporarily.

**Comment by DomT4** [comment]
Sure. Do you want those tests in one commit in one PR, or three separate commits in the one PR? Not sure which works best for the bot.

**Comment by mikemcquaid** [comment]
One commit, probably.

**Comment by DomT4** [comment]
Pushed https://github.com/Homebrew/homebrew/pull/36327

**Comment by DomT4** [comment]
Still failing here:

```
==> brew install --verbose --build-bottle mlite				 FAILED
Error: mlite is a devel-only formula
Install with `brew install --devel mlite`
==> brew audit mlite							 FAILED
Error: 1 problems in 1 formulae
mlite:
 * Devel-only (no stable download)
```

**Pull request closed without merging**
