### PR TITLE
elm-format 0.3.1-alpha

### PR DESCRIPTION
**Pull request by vorce**

### CODE REVIEW

**Comment by DomT4** [comment]
Test is failing here, did upstream rename the executable or anything like that?
```
==> /usr/local/Cellar/elm-format/0.3.0-alpha/bin/elm-format /tmp/elm-format-test-20160516-3706-emreii/Hello.elm --yes
Failed to execute: /usr/local/Cellar/elm-format/0.3.0-alpha/bin/elm-format
Error: homebrew/devel-only/elm-format: failed
```

**Comment by vorce** [comment]
Investigating, but yeah I suspect that is the case. I think it's two executables called elm-format-0.17 and elm-format-0.16 now. Going to verify and fix the PR.

**Comment by ilovezfs** [comment]
hmmm not sure that's the right fix

https://github.com/avh4/elm-format/blob/master/install_system.sh

Upstream still seems to expect a generically named executable to be there for installation.

**Comment by vorce** [comment]
I built it from source according to https://github.com/avh4/elm-format#building-from-source and that generated two executables, `elm-format-0.17` and `elm-format-0.16` - but `elm-format`. Perhaps the `install_system.sh` script is not updated? Or maybe something else is going on... how can I run the homebrew test myself?

**Comment by ilovezfs** [comment]
`brew test -vd elm-format`

**Comment by ilovezfs** [comment]
@vorce yup you're right. That's an upstream bug in that script.
https://github.com/avh4/elm-format/commit/8b7e75681ad616958bb3e06910a1b565a8aacf54

**Comment by vorce** [comment]
Trying to get my local env to reproduce the error (currently on brew install). But the error from Jenkins looks a bit strange.
```
==> brew audit homebrew/devel-only/elm-format
==> FAILED
Error: 1 problem in 1 formula
homebrew/devel-only/elm-format:
  * Devel-only (no stable download)
```

What does that mean?

**Comment by DomT4** [comment]
That's an error in our `audit` code apparently, I'll look at it.

**Comment by vorce** [comment]
Thanks @DomT4, I managed to reproduce it locally by just following what Jenkins did:

```
brew pull --clean https://github.com/Homebrew/homebrew-devel-only/pull/45
brew readall homebrew/devel-only
brew uses homebrew/devel-only/elm-format
brew fetch --retry homebrew/devel-only/elm-format --build-bottle --force
brew install --only-dependencies --build-bottle --devel --verbose homebrew/devel-only/elm-format
brew install --build-bottle --devel --verbose homebrew/devel-only/elm-format
brew audit homebrew/devel-only/elm-format
homebrew/devel-only/elm-format:
  * Devel-only (no stable download)
Error: 1 problem in 1 formula
```

`test` seems to work:
```
brew test -vd homebrew/devel-only/elm-format
/usr/local/Library/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-devel-only/Formula/elm-format.rb
Testing homebrew/devel-only/elm-format
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160516-61094-aipmv7.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-devel-only/Formula/elm-format.rb -vd --devel
/usr/local/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /usr/local/Library/Taps/homebrew/homebrew-devel-only/Formula/elm-format.rb
==> /usr/local/Cellar/elm-format/0.3.0-alpha/bin/elm-format-0.17 /tmp/elm-format-test-20160516-61095-7am149/Hello.elm --yes
Processing file /tmp/elm-format-test-20160516-61095-7am149/Hello.elm
```

**Comment by DomT4** [comment]
https://github.com/Homebrew/brew/pull/248 should fix the `audit` issue.

**Comment by vorce** [comment]
@BrewTestBot test this please.

**Comment by ilovezfs** [comment]
@vorce once  https://github.com/Homebrew/homebrew-devel-only/pull/46 passes and is merged, you can rebase on it, which should fix the current failure you're seeing for CI.

**Comment by vorce** [comment]
@ilovezfs cool, thanks

**Comment by ilovezfs** [comment]
@vorce If you rebase this on master now, it should build, fingers crossed.

**Comment by vorce** [comment]
It builds! :fireworks:

**Comment by DomT4** [comment]
@ilovezfs Will leave this one to you. 🚢 whenever you're happy.

**Comment by ilovezfs** [comment]
@vorce Do you mind updating this with https://github.com/avh4/elm-format/releases/tag/0.3.1-alpha first?

**Comment by vorce** [comment]
@ilovezfs sure thing.

**Comment by ilovezfs** [comment]
@vorce Thanks!

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/homebrew-devel-only/commit/55c4e6752f65fd42d024baeb2d5cb39197f11ba4

**Comment by ilovezfs** [comment]
@vorce Thanks for your contribution to Homebrew! (and especially for your patience)

**Pull request closed without merging**
