### PR TITLE
Libmill: Go-style concurrency in C

### PR DESCRIPTION
**Pull request by benjolitz**
Create a recipe that will allow for building of libmill (http://libmill.org/) on OSX that passes tests and is suitable for development.

### CODE REVIEW

**Comment by benjolitz** [comment]
I don't know why it claims there are no tests, when clearly there are. 

The tests passed correctly in Homebrew/homebrew as a pull request.

@DomT4 Do you know why homebrew-devel-only cannot see the test vector that clearly exists in this formula?

**Comment by tdsmith** [comment]
Jenkins is flaky (that's a Jenkins error, not a Homebrew error); I kicked off a new build for you.

**Comment by benjolitz** [comment]
Same error as before.

**Comment by tdsmith** [comment]
No, now it's failing an audit check: http://bot.brew.sh/job/Homebrew%20Devel-Only%20Pull%20Requests/84/testReport/

```
== /usr/local/Library/Taps/homebrew/homebrew-devel-only/Formula/libmill.rb ==
C: 16:  1: Extra blank line detected.

1 file inspected, 1 offense detected
```

**Comment by DomT4** [comment]
Click through to the link. It's fine this time, passed on ML, failed on Mavericks and Yosemite with:

```
== /usr/local/Library/Taps/homebrew/homebrew-devel-only/Formula/libmill.rb ==
C: 16:  1: Extra blank line detected.

1 file inspected, 1 offense detected
```

**Comment by DomT4** [comment]
Oops. Tim's comment wasn't there when I hit the `comment` button. Apologies for the double team.

**Comment by benjolitz** [comment]
Need a build kicked off. Jenkins has again said 'No test results'.

**Comment by DomT4** [comment]
It did indeed crash, but please note `no test results` is meaningless. You have to click through to the link either via the red cross (or green tick) or the "Details" button to see actual results.

**Comment by benjolitz** [comment]
It passed.

**Comment by benjolitz** [comment]
ping

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-devel-only/commit/558a906b8d8ce26668b3ee4f3f9486e366518183. Thank you for your contribution to Homebrew, we appreciate it! :smiley_cat:

**Pull request closed without merging**
