### PR TITLE
j2objc: reconfigure to new devel-only block standard

### PR DESCRIPTION
**Pull request by DomT4**

### CODE REVIEW

**Comment by DomT4** [comment]
Odd failure here. Perhaps something wrong with the ` install ` fix we merged the other day, although I didn't have any problems when I tested it locally at the time repeatedly. Weird.

```
Error: undefined method `requirements' for nil:NilClass
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/cmd/test-bot.rb:323:in `satisfied_requirements?'
/usr/local/Library/Homebrew/cmd/test-bot.rb:370:in `formula'
/usr/local/Library/Homebrew/cmd/test-bot.rb:571:in `block in run'
/usr/local/Library/Homebrew/cmd/test-bot.rb:570:in `each'
/usr/local/Library/Homebrew/cmd/test-bot.rb:570:in `run'
/usr/local/Library/Homebrew/cmd/test-bot.rb:703:in `test_bot'
/usr/local/Library/brew.rb:135:in `<main>'
Build step 'Execute shell' marked build as failure
Recording test results
ERROR: Publisher hudson.tasks.junit.JUnitResultArchiver aborted due to exception
hudson.AbortException: No test report files were found. Configuration error?
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:116)
```

@mikemcquaid

**Comment by mikemcquaid** [comment]
Should be fixed in https://github.com/Homebrew/homebrew/commit/198b7c1d075a40b1b2e5f7a831d76dfba605f43f. Have kicked off a new build.

**Comment by DomT4** [comment]
Thanks for the fix! :smiley_cat: 

Can we do anything about the ` test-bot ` flagging the builds as needing to be triggered with ` --devel `? An autotrigger perhaps?

**Comment by mikemcquaid** [comment]
Folks need to submit fixes to `brew-test-bot.rb` for this. Should be pretty easy to reproduce locally: `brew pull https://github.com/Homebrew/homebrew-devel-only/pull/8; brew test-bot j2objc --skip-setup` or similar.

**Comment by DomT4** [comment]
Will take a peek at the Bot's code and see if I can do anything useful on this.

**Pull request closed without merging**
