### PR TITLE
rebar3 beta-4

### PR DESCRIPTION
**Pull request by niku**
https://github.com/rebar/rebar3/releases/tag/beta-4

### CODE REVIEW

**Comment by dunn** [comment]
```
==> Finishing up
ln -s ../Cellar/rebar3/4/bin/rebar3 rebar3
==> Summary
☕️ 🐸  /usr/local/Cellar/rebar3/4: 4 files, 804K, built in 22 seconds
```
It's scanning the version as `4`; we should probably add `version "beta-4"` or even `version "3.0.0-beta-4"`.

**Comment by niku** [comment]
Thank you for your quick advice!

I add `:version => "beta-4"`,
And `brew reinstall rebar3 -v`.

```
==> Cleaning
==> Finishing up
ln -s ../Cellar/rebar3/3.0.0/bin/rebar3 rebar3
==> Summary
🍺  /usr/local/Cellar/rebar3/3.0.0: 4 files, 804K, built in 28 seconds
```

It seems OK.
Would you check it again?

**Comment by dunn** [comment]
Oh, sorry, I meant like:
```ruby
    url "https://github.com/rebar/rebar3.git",
        :tag => "3.0.0-beta.4",
        :revision => "356ac5033d12b8b91ed0d6c4d308b00070ab12b9"
    version "3.0.0-beta4"
```

**Comment by niku** [comment]
Oh, I was misunderstanding your comment. Sorry :disappointed: 
I updated the Fomula.

```
==> Finishing up
ln -s ../Cellar/rebar3/3.0.0-beta-4/bin/rebar3 rebar3
==> Summary
🍺  /usr/local/Cellar/rebar3/3.0.0-beta-4: 4 files, 804K, built in 23 seconds
```

It seems OK. (I wish :smirk: )
Would you check it?

**Comment by dunn** [comment]
Looks great! Merged in b12f533b49c218db7abbb38800383d91c611d0d5.

**Comment by niku** [comment]
Thank you for the kindly advice :heart:

**Pull request closed without merging**
