### PR TITLE
Hana 0.7.0

### PR DESCRIPTION
**Pull request by ldionne**
Update the formula to fetch the latest version of the Hana library, which is now 0.7.0.

### CODE REVIEW

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by ldionne** [comment]
I'll close this, since I'm releasing Hana in version 1.0.0 in the next days. Once that's done, I'll submit a PR to remove Hana from homebrew-devel-only and a PR to add it to the regular Homebrew.

**Comment by DomT4** [comment]
Sorry I forgot about this @ldionne. Please do feel free to nag me if I take more than a few days to re-review something. Homebrew is a lot of of work and it's easy to forget individual PRs sadly.

**Comment by ldionne** [comment]
No worries!

**Pull request closed without merging**
