### PR TITLE
Add docker-swarm 0.0.1 (new formula)

### PR DESCRIPTION
**Pull request by radeksimko**
I tried to come up with more meaningful tests, but all subcommands really require a connection to a cluster:

```
$ docker-swarm l
FATA[0000] --discovery required to list a cluster       
$ docker-swarm m
FATA[0000] --discovery required to manage a cluster     
$ docker-swarm j
FATA[0000] --discovery required to join a cluster 
```

and calling `docker-swarm c` effectively means just calling an API which returns a random token later used when making each node part of a new cluster.
https://github.com/docker/swarm#example-usage

### CODE REVIEW

**Comment by DomT4** [comment]
LGTM. I'd like to wait on https://github.com/Homebrew/homebrew/pull/36030 being merged so we can actually have the devel builds tested properly, and not just skipped over. We'll hopefully get that done in the next few days and then I'll get this re-tested and hopefully merge it at that point.

After https://github.com/Homebrew/homebrew/pull/36030 the setup here should be much more stable, and consequently PRs will get processed a little quicker than currently.

**Comment by DomT4** [comment]
@mikemcquaid Can you ask the bot to re-test this please? :heart:. The bot just ignores me when I ask :grinning:

**Comment by mikemcquaid** [comment]
@DomT4 Done. Do you see a `Rebuild` button on http://bot.brew.sh/job/Homebrew%20Devel-Only%20Pull%20Requests/26/?

**Comment by DomT4** [comment]
@mikemcquaid Thanks! I think there's one in ` head-only ` pending similar if you have the time. Nope, no rebuild button.

**Comment by mikemcquaid** [comment]
@DomT4 Try making yourself public here: https://github.com/orgs/Homebrew/people and it might give you permission.

**Comment by DomT4** [comment]
Done :+1:. Nothing yet on the test-bot, but I'll wait on the Bot to process this new rebuild and see if the button appears.

**Comment by DomT4** [comment]
That's weird. It's still showing all the errors from the previous bot test:

```
==> brew install --only-dependencies --verbose --build-bottle docker-swarm FAILED
Error: docker-swarm has no stable download, please choose --devel or --HEAD
==> brew install --verbose --build-bottle docker-swarm			 FAILED
Error: docker-swarm has no stable download, please choose --devel or --HEAD

==> brew audit docker-swarm --strict					 FAILED
==> brew style docker-swarm

1 file inspected, no offenses detected
Error: 1 problems in 1 formulae

==> audit problems
docker-swarm:
 * Devel-only (no stable download)
```

But I can't reproduce this locally at all, even using the same commands the bot is using. Any ideas? :confused:

**Comment by mikemcquaid** [comment]
Retrying just in case it was using the old version for some reason.

**Comment by DomT4** [comment]
There does appear to be a build error with this PR:

```
==> Checking out revision fa6674abf3f4580b946a01bf7a1ce4ba8766205b
git checkout-index -a -f --prefix=/private/tmp/docker-swarm--github.com-samuel-go-zookeeper-HIXOm6/
==> go build -o docker-swarm
# github.com/docker/swarm/cluster
src/github.com/docker/swarm/cluster/node.go:97: not enough arguments in call to n.client.StartMonitorEvents
src/github.com/docker/swarm/cluster/node.go:272: not enough arguments in call to n.client.StartMonitorEvents
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: go build -o docker-swarm
```

But if I do something like:

```
brew test-bot --skip-setup mlite
==> brew tests								 PASSED
==> brew readall							 PASSED
==> brew uses mlite							 PASSED
==> brew fetch --retry --build-bottle mlite				 PASSED
==> brew install --verbose --build-bottle --devel mlite			 PASSED
==> brew audit mlite							 PASSED
==> brew bottle --rb mlite						 FAILED
Error: Formula has no stable version: mlite
==> brew test --verbose mlite						 PASSED
==> brew uninstall --force mlite					 PASSED
```

**Comment by DomT4** [comment]
@radeksimko If you can double check the build failure I referenced in the top half of the above comment, I'll merge this. It could take a little while for us to sort out the bot's misbehaviour, and this has waited a while already.

**Comment by radeksimko** [comment]
> There does appear to be a build error with this PR

It seems it was an upstream issue with either swarm or some dependencies.
I've updated both and it looks fine now.

**Comment by DomT4** [comment]
Merged! Thanks for the patience. Appreciated.

Apologies on my part, I definitely should have caught this before I merged, but the version should go inside the devel block in future.

**Comment by radeksimko** [comment]
> the version should go inside the devel block in future.

ah, good point, I will keep that in mind next time.

**Pull request closed without merging**
