### PR TITLE
shadowvpn 0.1.6

### PR DESCRIPTION
**Pull request by DomT4**
Bump

### CODE REVIEW

**Comment by DomT4** [comment]
@mikemcquaid No dice on the bot fixes you pushed last week :cry: -

```
==> brew fetch --retry --build-bottle --force shadowvpn			 PASSED
==> brew install --only-dependencies --verbose --build-bottle shadowvpn	 FAILED
Error: shadowvpn is a devel-only formula
Install with `brew install --devel shadowvpn`
==> brew install --verbose --build-bottle shadowvpn			 FAILED
Error: shadowvpn is a devel-only formula
Install with `brew install --devel shadowvpn`
==> brew audit shadowvpn						 FAILED
Error: 1 problems in 1 formulae
shadowvpn:
 * Devel-only (no stable download)
```

**Comment by mikemcquaid** [comment]
@DomT4 Ok, I'll try and dig in on this when I get the chance.

**Comment by DomT4** [comment]
Thanks Mike. I'll keep being a test-bot locally until we iron this out, It's not too much of a pain given the relatively low volume of PRs here currently.

**Comment by mikemcquaid** [comment]
@DomT4 Fixed in https://github.com/Homebrew/homebrew/commit/b42c5c0b2112afe19a2d88d4d7b0d836852e47da.

**Comment by DomT4** [comment]
@mikemcquaid Nice! Thanks! Do we need to do something similar for ` test-bot.rb ` to pass the correct ` --devel ` flag or?

**Comment by mikemcquaid** [comment]
I don't think so, no, but ping me on the next PR that has issues.

**Comment by DomT4** [comment]
Cool, will do. Thanks Mike.

**Pull request closed without merging**
